---------------ASSIGNMENT-8----------------------

USE MY_EMPLOYEE;
SELECT * FROM EMP;
SELECT * FROM EMPSAL;

--A-1 :-
SELECT EMPID, NAME, CITY 
FROM EMP
WHERE CITY = 'GURGAON';
  --------- OR USING SUB-QUERIES -------
SELECT EMPID, NAME, CITY FROM EMP
WHERE EMPID IN ( SELECT EMPID FROM EMP WHERE CITY = 'GURGAON')

--A-2 :-
SELECT EMP.EMPID, NAME, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DESI LIKE '%MANAGER%';
  -------- OR USING SUB-QUERIES --------
SELECT EMP.EMPID, NAME, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DESI IN (SELECT DESI FROM EMPSAL WHERE DESI LIKE '%MANAGER%');

--A-3 :-
UPDATE EMPSAL SET SALARY = (SALARY - (SALARY * 0.1))
WHERE EMPID IN (SELECT EMPID FROM EMP WHERE CITY = 'DELHI');
SELECT EMP.EMPID, NAME, CITY, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE CITY = 'DELHI';

--A-4 :-
SELECT EMP.EMPID, NAME, CITY, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DEPT IN (SELECT EMPSAL.DEPT 
				FROM EMPSAL
				INNER JOIN EMP
				ON EMP.EMPID = EMPSAL.EMPID
				WHERE NAME = 'DAVID' OR NAME = 'RAMESH SHARMA');

--------- USING CO-RELATED SUBQUERY--------------
SELECT EMP.EMPID, NAME, CITY, DOJ, DEPT, DESI, SALARY
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DEPT IN (SELECT DEPT FROM EMPSAL
				WHERE EMPID IN (SELECT EMPID FROM EMP
								WHERE NAME = 'DAVID' OR NAME = 'RAMESH SHARMA'));

--A-5 :-
CREATE TABLE TRAINING
(EID CHAR(5),
NAME VARCHAR(30),
DEPT CHAR (5));

INSERT INTO TRAINING (EID,NAME,DEPT)
(SELECT EMP.EMPID, NAME, DEPT 
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DEPT IN (SELECT DEPT FROM EMPSAL WHERE DEPT = 'OPS')); 

SELECT * FROM TRAINING;

--A-6 :-
DELETE FROM TRAINING
WHERE EID IN (SELECT EMPID FROM EMPSAL WHERE DESI LIKE '%DIRECTOR%');

--A-7 :-
SELECT * FROM EMPSAL
WHERE DEPT IN (SELECT DEPT FROM EMPSAL WHERE SALARY > 200000);