--ASSIGNMENT 4

USE MY_EMPLOYEE;

SELECT * FROM EMP;

SELECT CITY, COUNT(EMPID) AS 'CITYWISE COUNT' FROM EMP
GROUP BY CITY
ORDER BY COUNT(EMPID) DESC;

SELECT * FROM EMP
WHERE EMAIL NOT LIKE '%YAHOO%';

SELECT * FROM EMPSAL;


SELECT DESI, SUM(SALARY) AS 'TOTAL COST', COUNT(EMPID) AS 'TEAM SIZE' FROM EMPSAL
GROUP BY DESI
ORDER BY 'TOTAL COST' DESC;