-----------ASSIGNMENT 7.1----------------

USE MY_EMPLOYEE;

SELECT * FROM EMP;
SELECT * FROM EMPSAL;

--A-1 :-
SELECT DEPT, COUNT(EMPID) AS 'TEAMSIZE', AVG(SALARY) AS 'AVERAGE SALARY' 
FROM EMPSAL
GROUP BY DEPT;

--A-2 :-
SELECT COUNT(EMPID) AS 'MANAGERS COUNT' FROM EMPSAL
WHERE DESI LIKE '%MANAGER%';

--A-3 :-
SELECT MAX(SALARY) AS 'MAXIMUM SALARY OF AN ASSOCIATE', MIN(SALARY) AS 'MINIMUM SALARY OF AN ASSOCIATE'
FROM EMPSAL
WHERE DESI LIKE '%ASSOCIATE%';

--A-4 :-
SELECT DEPT, COUNT(EMP.EMPID) AS 'DEPT SIZE', AVG(SALARY) AS 'AVERAGE SALARY'
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID=EMPSAL.EMPID
WHERE CITY = 'DELHI'
GROUP BY DEPT;

--A-5 :-
SELECT NAME, UPPER(CONCAT(
							LEFT(NAME,1),
							SUBSTRING (NAME, CHARINDEX(' ', NAME) + 1, 1),
							RIGHT(EMPID,3),
							'@RCG.COM'
						  )) AS 'OFFICIAL MAIL ID' 
FROM EMP;

--A-6 :-
SELECT NAME, CITY, PHNO, EMAIL FROM EMP
WHERE DATEDIFF(YEAR,DOB,GETDATE())>=40;

--A-7 :-
SELECT EMP.EMPID, NAME, DOJ 
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID =  EMPSAL.EMPID
WHERE DATEDIFF(YEAR,DOJ,GETDATE())>5;

--A-8 :-
SELECT EMP.EMPID, NAME, DEPT, DESI, CITY, PHNO, DOB  
FROM EMP
INNER JOIN EMPSAL
ON EMP.EMPID = EMPSAL.EMPID
WHERE DESI LIKE '%MANAGER%' AND DATEPART(MONTH,DOB) = DATEPART(MONTH,GETDATE());

--A-9 :-
SELECT EMPID, DEPT, DESI, SALARY FROM EMPSAL
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPSAL);

--A-10 :-
SELECT EMPID, NAME FROM EMP
WHERE LEN(NAME) = (SELECT MAX(LEN(NAME)) FROM EMP);


------------------ASSIGNMENT 7.2------------------

--A-1 :-
CREATE FUNCTION CAL(@X AS INT, @Y AS INT, @O AS CHAR(1))
RETURNS INT
AS
BEGIN
	DECLARE @R AS INT
	IF @O = '+'
		SET @R = @X + @Y;
	ELSE IF @O = '-'
		SET @R = @X - @Y;
	ELSE IF @O = '*'
		SET @R = @X * @Y;
	ELSE IF @O = '/'
		SET @R = @X / @Y;
	ELSE IF @O = '%'
		SET @R = @X % @Y;
	ELSE
		SET @R = 0;
	RETURN @R;
END;
SELECT DBO.CAL(20,15,'+') AS 'ADDITION'
SELECT DBO.CAL(20,15,'-') AS 'SUBTRACTION'
SELECT DBO.CAL(20,15,'*') AS 'MULTIPLICATION'
SELECT DBO.CAL(20,15,'/') AS 'DIVISION'
SELECT DBO.CAL(20,15,'%') AS 'MODULUS'
SELECT DBO.CAL(20,15,'') AS 'NONE'

------

--A-2 :-
CREATE FUNCTION OFFICIAL_MAIL (@NAME AS VARCHAR(30), @EMPID AS CHAR(5))
RETURNS VARCHAR(13)
AS
BEGIN
	DECLARE @MAIL AS VARCHAR(13);
	SET @MAIL = CONCAT(
						LEFT(@NAME,1),
						SUBSTRING(@NAME, CHARINDEX(' ',@NAME) +1, 1),
						RIGHT(@EMPID,3),
						'@RCG.COM');
	RETURN @MAIL
END;
SELECT DBO.OFFICIAL_MAIL('SASIKUMAR V','E0003') AS 'OFFICIAL MAIL';

-------

---A-3 :-
CREATE FUNCTION EMP_DETAILS (@DEPT AS VARCHAR(20))
RETURNS TABLE
AS
	RETURN(
			SELECT EMP.EMPID, NAME, DESI, DEPT, SALARY
			FROM EMP
			INNER JOIN EMPSAL
			ON EMP.EMPID = EMPSAL.EMPID
			WHERE DEPT = @DEPT 
			);

SELECT * FROM DBO.EMP_DETAILS('HR')
SELECT * FROM EMPSAL

----------

---A-4 :-
CREATE FUNCTION BIRTHDAY()
RETURNS TABLE
AS
	RETURN(
			SELECT EMP.EMPID, NAME, DEPT, DESI, CITY 
			FROM EMP
			INNER JOIN EMPSAL
			ON EMP.EMPID = EMPSAL.EMPID
			WHERE DATEPART(MONTH, EMP.DOB) = DATEPART(YEAR, GETDATE())
			);

SELECT * FROM DBO.BIRTHDAY();

------------

--A-5 :-
CREATE FUNCTION SENIOR_EMP()
RETURNS TABLE
AS
	RETURN(
			SELECT EMP.EMPID, NAME, DEPT, DOJ
			FROM EMP
			INNER JOIN EMPSAL
			ON EMP.EMPID = EMPSAL.EMPID
			WHERE DATEDIFF(YEAR,DOJ,GETDATE()) > 5
			);

SELECT * FROM DBO.SENIOR_EMP();

