
-- ASSIGNMENT 3

CREATE DATABASE MY_EMPLOYEE;
USE MY_EMPLOYEE;

--IMPORTING TWO CSV FILES: EMP & EMPSAL AS FLAT FILES BEFORE PROCEDDING :-

SELECT * FROM EMP;
SELECT * FROM EMPSAL;

ALTER TABLE EMP
ALTER COLUMN DOB DATE;

ALTER TABLE EMPSAL
ALTER COLUMN DOJ DATE;

--NOW ADDING CONSTRAINTS :-

ALTER TABLE EMP
ADD CONSTRAINT PKID PRIMARY KEY (EMPID);

ALTER TABLE EMP
ALTER COLUMN NAME VARCHAR(30) NOT NULL;

ALTER TABLE EMP
ADD CONSTRAINT CKADD CHECK (ADDR NOT LIKE '%UTTAM NAGAR%');

ALTER TABLE EMP
ADD CONSTRAINT CKCITY CHECK (CITY IN ('DELHI','GURGAON','NOIDA',
									  'CHANDIGARH','DEHRADUN','MUMBAI'));

ALTER TABLE EMP
ADD CONSTRAINT UQPH UNIQUE (PHNO);

ALTER TABLE EMP
ADD CONSTRAINT CKMAIL CHECK (EMAIL LIKE '%@GMAIL%' OR 
							 EMAIL LIKE '%@YAHOO%' OR
							 EMAIL LIKE '%@OUTLOOK%');

ALTER TABLE EMP
ADD CONSTRAINT CKDOB CHECK (DOB <= '01-01-2002');

SELECT * FROM EMP;

------------------------------------------------------------------

SELECT * FROM EMPSAL;
SELECT DISTINCT DESI FROM EMPSAL;

ALTER TABLE EMPSAL
ADD CONSTRAINT FKID FOREIGN KEY (EMPID) REFERENCES EMP (EMPID);

ALTER TABLE EMPSAL
ADD CONSTRAINT CKDEPT CHECK (DEPT IN ('ADMIN','HR','IT','MIS','OPS','TEMP'));

ALTER TABLE EMPSAL
ADD CONSTRAINT CKDESI CHECK (DESI IN ('ASSOCIATE','Manager','VP','Director',
									  'ASSISTANT MANAGER','SENIOR ASSOCIATE','SENIOR MANAGER'));

ALTER TABLE EMPSAL
ADD CONSTRAINT CKSAL CHECK (SALARY >= 20000);

ALTER TABLE EMPSAL
ADD CONSTRAINT defdept default 'TEMP' for dept

SELECT * FROM EMPSAL;







