--ASSIGNMENT 5

USE MY_EMPLOYEE;

SELECT * FROM EMP;
SELECT * FROM EMPSAL;

SELECT EMP.EMPID, NAME, CITY, DOJ, DEPT, DESI, SALARY
FROM EMP 
INNER JOIN EMPSAL
ON EMP.EMPID=EMPSAL.EMPID
WHERE CITY = 'DELHI';

---------------------------------------------------------------------

SELECT EMP.EMPID, NAME, ADDR, CITY, PHNO, EMAIL, DOB, SALARY
FROM EMP 
FULL JOIN EMPSAL
ON EMP.EMPID=EMPSAL.EMPID
WHERE SALARY IS NULL;


---------------------------INVENTORY-----------------------------------

